VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GDT27W7EZNXXI3O4JRX6TC5WJPAJYRAIFPU2PCFTZ7XZTQH7FAUTNQEN"
]

[DOCUMENTATION]
ORG_NAME="Cowboys"
ORG_DESCRIPTION="Cowboys are ready to become the next crypto millionaire"
ORG_DBA="cowboys007.github.io"
ORG_URL="https://cowboys007.github.io"
ORG_LOGO="https://cowboys007.github.io/img/Cowboys.png"
ORG_OFFICIAL_EMAIL="Cowboys007@gmail.com"

[[PRINCIPALS]]
name="Cowboys"
email="Cowboys007@gmail.com"
github="Cowboys007"

[[CURRENCIES]]
code="COW"
name="Cowboys"
issuer="GDT27W7EZNXXI3O4JRX6TC5WJPAJYRAIFPU2PCFTZ7XZTQH7FAUTNQEN"
desc="Cowboys are ready to become the next crypto millionaire"
conditions="Withdrawal fees apply"
image="https://cowboys007.github.io/img/Cowboys.png"
status="live"
anchor_asset="BTC"
anchor_asset_type="crypto"
display_decimals=7
regulated=true
is_asset_anchored=true
is_unlimited=false
