VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GAX46QEMVKRQKREMHQXGDF2YLOTHVY76JKZPQPV2MVIQI43EKK7SHCCZ",
"GBMUGKI6P4QKNHX5GMKKWDD746WP3HUM5SPH5MSNZUW3VXDTA6S4ALDZ",
"GANJ2WWTQXBHN4ICQJEQZCOHQFGNFWUSONZ3ZLIJIEVRYJ57ELO4JDRY",
"GCM4UG6QYYNRFIM424WIQEAD5J6YQOKCWW4M7MPMT7IYRV5RQXDTJCGF"
]

[DOCUMENTATION]
ORG_NAME="Cowboys"
ORG_DESCRIPTION="Cowboys are ready to become the next crypto millionaire"
ORG_DBA="Cowboys.github.io"
ORG_URL="https://Cowboys.github.io"
ORG_LOGO="https://Cowboys.github.io/img/Cowboys.png"
ORG_OFFICIAL_EMAIL="Cowboys007@gmail.com"

[[PRINCIPALS]]
name="Cowboys"
email="Cowboys007@gmail.com"
github="Cowboys007"

[[CURRENCIES]]
code="COW"
name="Cowboys"
issuer="GAX46QEMVKRQKREMHQXGDF2YLOTHVY76JKZPQPV2MVIQI43EKK7SHCCZ"
desc="Cowboys are ready to become the next crypto millionaire"
conditions="Withdrawal fees apply"
image="https://Cowboys.github.io/img/Cowboys.png"
status="live"
anchor_asset="BTC"
anchor_asset_type="crypto"
display_decimals=7
regulated=true
is_asset_anchored=true
is_unlimited=false
